### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Gunjanrathore8178** [2devyank/Hackto-Projects#1]
I can make changes on the home/landing page so that the page looks more attractive and informative using html and css. Please assign this project to me.

**Comment by 2devyank** [comment]
@Gunjanrathore8178 go ahead

**Comment by Gunjanrathore8178** [comment]
I hope this is being a bit formal and attractive as well and also there's a text on the small images that is "flip this over" which directly gives instruction to the user.
